FactoryGirl.define do
  factory :product do
    #title "MyString" #autogenerated
    #price "9.99" #autogenerated
    #published false #autogenerated
    #user_id 1 #autogenerated
    title { FFaker::Product.product_name }
    price { rand() * 100 }
    published false
    user_id "1" #hardcoded temporarely
  end


end
